[project]
name = "option-mean"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "joblib>=1.5.2",
    "polars>=1.35.2",
    "polars-ols>=0.3.5",
    "seaborn>=0.13.2",
    "tqdm>=4.67.1",
]
